version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_DB: users_db  # Ensure this is set to your intended database
    ports:
      - '5432:5432'
    volumes:
      - group-project:/var/lib/postgresql/data 
      - ./init_data:/docker-entrypoint-initdb.d 

  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository  
    command: 'npm run testandrun'

volumes:
  group-project:
